### ISSUE TITLE
Merge command has wrong branch name

### ISSUE THREAD

**Issue by miltosZ** [MicrosoftDocs/devops-resource-center#101]
HI there,
Expected git merge command differs from the actual.
Expected: git merge cool-new-feature main
Actual: git merge cool-feature main

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b6c7f339-1705-5225-b913-b3009a429084
* Version Independent ID: a33e94de-6b69-2f20-2bcc-333739e75049
* Content: [Understand Git history - Azure DevOps](https://learn.microsoft.com/en-us/devops/develop/git/understand-git-history)
* Content Source: [docs/develop/git/understand-git-history.md](https://github.com/MicrosoftDocs/devops-resource-center-pr/blob/live/docs/develop/git/understand-git-history.md)
* Service: **azure-devops**
* Sub-service: **devops-resource-center**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks! A update will roll out this week.
