### ISSUE TITLE
Feedback request: Process initiation of hotfix

### ISSUE THREAD

**Issue by mail2pradeepc** [MicrosoftDocs/devops-resource-center#102]
[ 
Hi,
My feedback is for 2nd para: ...A developer creates a branch from main..
Ideally the process must star from a defect/bug that causes this change initiation. So the start point of this change must be the bug/defect. The developer must then start branch creation process linking to the bug/defect. 
]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9e67f55-3915-bc7e-5d78-e7f0ee72a6f1
* Version Independent ID: 0280a766-ed9d-c9fe-9f86-d81f4eec26fe
* Content: [How Microsoft develops with DevOps - Azure DevOps](https://learn.microsoft.com/en-us/devops/develop/how-microsoft-develops-devops?view=azure-devops)
* Content Source: [docs/develop/how-microsoft-develops-devops.md](https://github.com/MicrosoftDocs/devops-resource-center-pr/blob/live/docs/develop/how-microsoft-develops-devops.md)
* Service: **azure-devops**
* Sub-service: **devops-resource-center**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks, I'm adding this request to another backlog request for more information on hotfixes.
