### ISSUE TITLE
Scrum page should reference the Scrum Guide

### ISSUE THREAD

**Issue by MrHinsh** [MicrosoftDocs/devops-resource-center#103]
This page should reference the Scrum Guide prominently! https://scrumguides.org.

This guide is maintained by the creators of Scrum, and is recognised as the core reference material by Scrum.org and Scrum Alliance!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd3e1175-0a29-6ffe-cda9-63f419faf371
* Version Independent ID: 54ff8cb0-4c46-a34b-969d-710f3404bd8c
* Content: [What is Scrum? - Azure DevOps](https://learn.microsoft.com/en-us/devops/plan/what-is-scrum)
* Content Source: [docs/plan/what-is-scrum.md](https://github.com/MicrosoftDocs/devops-resource-center-pr/blob/live/docs/plan/what-is-scrum.md)
* Service: **azure-devops**
* Sub-service: **devops-resource-center**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks for the request. We'll take it under consideration.

**Comment by MrHinsh** [comment]
@juliakm I'd also like to address the elements that are incorrect. There is a lot on here that goes against the tenants of Scrum, is just plane wrong, and often hit on common anti-patterns as a positive.

Where is best st start this conversation?

**Comment by pabrams** [comment]
> @juliakm I'd also like to address the elements that are incorrect. There is a lot on here that goes against the tenants of Scrum, is just plane wrong, and often hit on common anti-patterns as a positive.
> 
> Where is best st start this conversation?

I agree with your comment, but ...

~~tenants~~ tenets
also,
~~plane~~ plain

You never were much good at spelling, though your ranger service is legendary, Mr. Hinshelwood.

**Comment by MrHinsh** [comment]
Dyslexic :)
