### ISSUE TITLE
Image text has low contast in dark mode theme

### ISSUE THREAD

**Issue by mcsamuelshoko** [MicrosoftDocs/devops-resource-center#106]
- The  image is on the section  : **`DevOps and the application lifecycle
`** .
- the text in question is the capitalized **`PLAN`**, **`DEVELOP`**, **`DELIVER`**, **`OPERATE`**, and **`APPLICATION`** .
- the image has been linked in the issue 👇 

![image](https://learn.microsoft.com/en-us/devops/_img/devops-lifecycle.png)

[<https://learn.microsoft.com/en-us/devops/_img/devops-lifecycle.png>]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0cf98c4b-9185-00d5-a980-e2adb3e291fd
* Version Independent ID: f6005931-c9b5-48d9-e6c3-f835bb9b01b1
* Content: [What is DevOps? - Azure DevOps](https://learn.microsoft.com/en-us/devops/what-is-devops)
* Content Source: [docs/what-is-devops.md](https://github.com/MicrosoftDocs/devops-resource-center-pr/blob/live/docs/what-is-devops.md)
* Service: **azure-devops**
* Sub-service: **devops-resource-center**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thank you for the feedback! We'll replace the image this week.
