### ISSUE TITLE
Bad URL to hands-on-lab to learn the basics of GitHub

### ISSUE THREAD

**Issue by bjwyman** [MicrosoftDocs/devops-resource-center#107]
Learn the basics of GitHub in this [hands-on lab](https://lab.github.com/githubtraining/introduction-to-github).

404
There isn't a GitHub Pages site here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8bef1fc1-7307-0df8-601c-2545085ae6c7
* Version Independent ID: ab85f8b0-65b4-306d-e5cd-6737cc16fd8d
* Content: [Hosting Git in GitHub and Azure Repos - Azure DevOps](https://learn.microsoft.com/en-us/devops/develop/git/hosting-git-repos?view=azure-devops)
* Content Source: [docs/develop/git/hosting-git-repos.md](https://github.com/MicrosoftDocs/devops-resource-center-pr/blob/live/docs/develop/git/hosting-git-repos.md)
* Service: **azure-devops**
* Sub-service: **devops-resource-center**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks, the correct link is https://github.com/skills/introduction-to-github. An update will roll out this week.
