### ISSUE TITLE
Broken Link in What is CD Next Steps

### ISSUE THREAD

**Issue by mrmod** [MicrosoftDocs/devops-resource-center#108]
In the next steps section of the what is continuous delivery? Document the link to GitHub Actions 404s

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65da4c36-9580-2f30-758f-258f636abecc
* Version Independent ID: 6238066e-aa04-879f-1d9c-7fc3f1295fae
* Content: [What is continuous delivery? - Azure DevOps](https://learn.microsoft.com/en-us/devops/deliver/what-is-continuous-delivery)
* Content Source: [docs/deliver/what-is-continuous-delivery.md](https://github.com/MicrosoftDocs/devops-resource-center-pr/blob/live/docs/deliver/what-is-continuous-delivery.md)
* Service: **azure-devops**
* Sub-service: **devops-resource-center**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks! An update will roll out this week.
