### ISSUE TITLE
Outdated :( 

### ISSUE THREAD

**Issue by manb-msft** [MicrosoftDocs/devops-resource-center#12]
This page is pretty out-dated (yaml deployment is not updated, for example)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96200b4-9fc1-7d8c-dce4-6a2b0cb5fa4d
* Version Independent ID: bf8e5f2c-a8a5-d2e1-f89c-5ed5129c32a3
* Content: [Azure DevOps vs GitLab - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/compare/azure-devops-vs-gitlab#feedback)
* Content Source: [docs/compare/Azure-DevOps-vs-GitLab.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/compare/Azure-DevOps-vs-GitLab.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **davemcki**

**Comment by jrybacek** [comment]
I agree this is out-dated.  We are currently comparing CI/CD tools and it looks like Gitlab's comparison page was updated 3 months ago...  https://about.gitlab.com/devops-tools/azure-devops-vs-gitlab.html

**Comment by manb-msft** [comment]
Thanks @jrybacek . Please do let me know if I can help/contribute in any way.
