### ISSUE TITLE
What if post-checkin validation fails?

### ISSUE THREAD

**Issue by matthid** [MicrosoftDocs/devops-resource-center#17]
> After merge, we run additional acceptance tests that take more time to run. These are more like a traditional post-checkin tests and we use them to perform an even more thorough validation. This gives us a good balance between having fast tests during the pull request review yet still having complete test coverage before release.

Can you clarify how that scenario is handled in the Release Flow. In particular:
- What happens? (Email to developers?, Revert?)
- Who fixes the problem? (Original developer or developer assigned to release branch?)
- When are the tests run? (Daily?, after every merge? Both?)

Thanks for this article!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1235ec4-e7e9-b0c2-8f1f-ee9682175a05
* Version Independent ID: a473750a-fbb6-4eed-e0e6-34e8a5009507
* Content: [Release Flow - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow)
* Content Source: [docs/devops-at-microsoft/release-flow.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/devops-at-microsoft/release-flow.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **ethomson**

**Comment by mirsilstan** [comment]
I would be interested in the same thing.

**Comment by juliakm** [comment]
Looks like this article has since been updated.
