### ISSUE TITLE
Both links point to same URL, should they?

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/devops-resource-center#19]
The link target for both "cloning a single branch with history" and "cloning all branches with merge history" is the same. 

Since there's an "or" in between, it seems like this should be two separate target pages?

--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44afc4fe-66c8-a745-0037-00748a80beb7
* Version Independent ID: 0ea09401-6a08-d745-ff50-7a7b74c41f32
* Content: [Migrate from TFVC to Git - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/migrate-from-tfvc-to-git#feedback)
* Content Source: [docs/git/migrate-from-tfvc-to-git.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/git/migrate-from-tfvc-to-git.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **routlaw**

**Comment by NenoLoje** [comment]
@EdKaim How was this issue fixed?

**Comment by EdKaim** [comment]
The duplicate link was updated to point at the correct content.
