### ISSUE TITLE
Scrum Team != Development Team

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/devops-resource-center#20]
According to the [Scrum Guide](https://scrumguides.org) it is the development team that does the work, so let's change

1) "Scrum Team" to "Development Team" in:

```
Scrum Team

These are the individuals that actually build the product. The team owns the engineering of the product, and the quality that goes with it.
```

and

2) I suggest changing the section title to "Roles of a Scrum Team" (instead of "Scrum Rules) to reflect that Product Owner + Scrum Master + Development Team is the Scrum Team.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92be2bb1-d071-8531-4dea-75fbffdbe764
* Version Independent ID: 82b71f3e-48ee-6616-30eb-f939941807ea
* Content: [What is Scrum? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/agile/what-is-scrum#feedback)
* Content Source: [docs/agile/what-is-scrum.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/agile/what-is-scrum.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **samgu**

**Comment by juliakm** [comment]
This is an old issue but I've added a fix as part of a larger set of fixes. An update will go live in the next few days.
