### ISSUE TITLE
I disagree with the approach for hotfixes

### ISSUE THREAD

**Issue by gionkunz** [MicrosoftDocs/devops-resource-center#22]
I do not agree with the arguments in this article and I would advise not to follow those practices for the following main reasons:

1. How can I reliably implement a fix for the release code base when I need to develop in master with all the rest of the master changes going on?
2. Cherry picking results in completely different commit hashes and the two branches will diverge completely which makes it really hard to relate them in critical situations

> We always start by making the change in master first: this allows us to create the fix quickly, and validate it locally without having to switch to the release branch locally.

Switching to the release branch to implement a hotfix is also quick, I don't think there's anything wrong with that. I could be implementing the fix on master for a completely different code base than the one still on the release branch, this is really dangerous and I fully disagree with the Azure DevOps release flow documented here https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow#releasing-hotfixes

Just to visualize the Problem: Let's say we have file a.ts. We do Release 1 and after some time we discover a nasty bug, which we want to hotfix. We prepare a hotfix for file a.ts on master. Meanwhile file a.ts was refactored by an other person on master.

Scenario A) Now, we can't find the problem because the refactoring took care of it already
Scenario B) The problem is somewhat manifested differently because of the refactoring and the investigation and solution would not really be the same as with the release codebase in production
Scenario C) The changes of the refactoring made in file a.ts are completely isolated from the code part which caused the bug and is subject for hotfix

So for Scenario A, I would need to cherry pick the whole refactoring to production, probably along with some more files changes, because "Banana in the Jungle", really terrible idea. I will recognise this problem and fallback to my proposal, that it's crucial to perform hotfixes on the release branch (DevOps flow) or master branch (production version in git flow). For Scenario B, it would go roughly the same. I identify the problematic code, which is somewhat integrated differently in the code since the refactoring and I fix it on master. Then I try to cherry pick the refactored file with the fix on Release, which does not really work with all the refactoring and will need to tedious patching with a lot of uncertainty to get things right. Only in scenario C, where the fix is really isolated from the rest of the refactoring and the files are exactly the same in that part of the code, I will be able to follow this rather monkey patching approach.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1235ec4-e7e9-b0c2-8f1f-ee9682175a05
* Version Independent ID: a473750a-fbb6-4eed-e0e6-34e8a5009507
* Content: [Release Flow - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow#releasing-hotfixes)
* Content Source: [docs/devops-at-microsoft/release-flow.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/devops-at-microsoft/release-flow.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **ethomson**

**Comment by gionkunz** [comment]
I believe that the most important thing when providing hotfixes is reliability, determinability and complete traceability. Speed and minimizing possibilities for human errors (forget to merge back to master) are also important, but if you ask me, not as important as the first few I have mentioned. The idea of implementing a production fix from the development branch first and then use cherry pick, a concept that completely detaches related changes, is completely against those 3 mentioned concepts.

**Comment by firedeepan** [comment]
The same question came to my mind.

**Comment by saciervo** [comment]
I'd go for this advice in the [branch for release](https://trunkbaseddevelopment.com/branch-for-release/#cherry-picks-from-the-trunk-to-branch-only) article of the Trunk Based Development website. 

> Of course, sometimes you absolutely cannot reproduce the bug on trunk. In that case you have to do it the other way round, despite everything mentioned above, but understand you have introduced risk of regression.

So you would base your hotfix from the release branch instead of the master. Do the PR on the release branch and then cherry-pick it back to master.

**Comment by juliakm** [comment]
Closing as this content is no longer on the site.
