### ISSUE TITLE
Link missing in paragraph about Fault Injection Learnings 

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/devops-resource-center#26]
A link is missing in the section titled "**Fault Injection Learnings**"

It says:

> You want to automate the fault injection experiments, because these are expensive tests and the system is always changing. You can also find more information at .

... but there's no link after the "at".

Thanks!
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0f194c9-d99d-9b41-a562-5be1f93c1615
* Version Independent ID: 816d8c8c-6622-e6ba-c48f-dafb3080ea88
* Content: [Shift Right to Test in Production - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/shift-right-test-production)
* Content Source: [docs/devops-at-microsoft/shift-right-test-production.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/devops-at-microsoft/shift-right-test-production.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **routlaw**

**Comment by NenoLoje** [comment]
@EdKaim Was this issue fixed?

**Comment by EdKaim** [comment]
Yes, the link reference was removed during a recent update.
