### ISSUE TITLE
multiple false statements

### ISSUE THREAD

**Issue by InternetPseudonym** [MicrosoftDocs/devops-resource-center#3]
> "Git stores versions as a snapshot of the entire repository"

thats simply not true. GIT stores versions as snapshots of repositories - yes, but the snapshots themselves are differential in nature. The word "entire" is very misleading and simply .... false. GIT stores differentials on the storage level so even the individual snapshots arent actual files, they may very well be a binary diff, for instance.

This is a somewhat acceptable explanation : 
https://stackoverflow.com/a/8198276

also : 

> "and the metadata about how files change is not available"

now thats completely false. Every differential for every file is completely accessible - binaries like `git diff ` extract them on command. Granted : some differentials may be somewhat cumbersome to extract, given how complicated the storage concept can be - one could be forced to build a diff out of a single base-blob and several differentials, for example _(if the exact commit ID cannot be identified)_

In fact, GIT pretty much would'nt work without this "metadata", its the core concept. See the aforementioned explanation for a quick overview.

> Change types in TFVC like rename, undelete and rollback cannot be expressed in Git;

Again : thats wrong. All of these operations _(and more)_ can be expressed via a simple `checkout` - it even is possible to have a **completely** identical workspace each time if you use the `--force` option 
_(beware : `--force` **will** delete unversioned files)_

> instead of seeing that file A was renamed to file B, you may only see that file A was deleted and file B was added in the same commit

Yes, because the rename detection treshold may be chosen unwisely or the rename simply was too complex. See https://stackoverflow.com/a/7941544. Some IDEs have fixed parameters - sometimes they're not very ... "optimal" and cause rename detection failures or worse. I think that should be mentioned, this whole paragraph makes GIT look like some sort of "inferior" versioning system. 

> If you rely on TFVC labels to know what was delivered, Git tags may not be provide this information.

Completely false - GIT commits (and hence tags on them) are guaranteed to be unique. A delivered product from tag A will always be searchable and reproducible, a simple checkout will suffice 
**but**
if you choose to deliver a product which consists of "tag A plus commit X, Y and Z" ... well ... **thats a you-problem**

> In Git, a merge affects the entire repository, and you cannot see both sets of individual changes as a merge.

that doesnt make much sense - both "sets" are commits or sets of commits and - of course - add up to your merge, if merged together. Also : a merge certainly does **not** affect the "entire repository", that'd pretty much destroy most of it. Merges are sets of commits which get placed on top of another set (at least 1) of commits.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d05453e8-ded7-b09d-26c0-78906b16a67c
* Version Independent ID: 195d2303-45f4-e074-b234-67235219dc5a
* Content: [Plan your migration to Git - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/centralized-to-git#feedback)
* Content Source: [docs/git/centralized-to-git.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/git/centralized-to-git.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **samgu**

**Comment by InternetPseudonym** [comment]
also : 

> "and the metadata about how files change is not available"

now thats completely false. Every differentail for every file is completely accessible, binaries like `git diff `extract them

**Comment by juliakm** [comment]
Closing older issue. It looks like this content has all changed.
