### ISSUE TITLE
Goal setting of this article

### ISSUE THREAD

**Issue by jackhuangca** [MicrosoftDocs/devops-resource-center#30]
[Enter feedback here]
If the goal of Epics is to accomplish 60%, then 80% for features, and 90% for stories, then 95% for tasks, it means the team would only achieve 41% of the company's vision, do I miss anything here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4bc244f-e07c-f8a4-0f00-04c8e015821f
* Version Independent ID: 2a37fdcf-eac8-3738-af46-7d70826ec660
* Content: [Scale Agile to Large Teams - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/agile/scale-agile-large-teams)
* Content Source: [docs/agile/scale-agile-large-teams.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/agile/scale-agile-large-teams.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **samgu**

**Comment by juliakm** [comment]
Thanks for the feedback. It looks like this section is no longer in this article.
