### ISSUE TITLE
Question: How to auto create release branches with release flow

### ISSUE THREAD

**Issue by crh225** [MicrosoftDocs/devops-resource-center#36]
[Enter feedback here]
How can we automatically at the end of the sprint create a release branch with azure devops using the release flow process? Does microsoft do this manually at the end of the sprints?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1235ec4-e7e9-b0c2-8f1f-ee9682175a05
* Version Independent ID: a473750a-fbb6-4eed-e0e6-34e8a5009507
* Content: [Release Flow - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow)
* Content Source: [docs/devops-at-microsoft/release-flow.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/devops-at-microsoft/release-flow.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **ethomson**

**Comment by juliakm** [comment]
This is an old issue, but I would look into using a [trigger](https://learn.microsoft.com/azure/devops/pipelines/build/triggers?view=azure-devops) at the end of a release. You could potentially use a [scheduled trigger](https://learn.microsoft.com/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml) and then tag the release. Depending on your needs, you might want to explore [this extension](https://marketplace.visualstudio.com/items?itemName=liquorichris.tag-git-release).
