### ISSUE TITLE
HF question

### ISSUE THREAD

**Issue by gromano-akamai** [MicrosoftDocs/devops-resource-center#37]
[Enter feedback here]
Hi - what do you do if you need to have a HF released but without all new code which is on master currently and still in development ? i didn't see any comments on this scenario. 

Gabby

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1235ec4-e7e9-b0c2-8f1f-ee9682175a05
* Version Independent ID: a473750a-fbb6-4eed-e0e6-34e8a5009507
* Content: [Release Flow - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow)
* Content Source: [docs/devops-at-microsoft/release-flow.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/devops-at-microsoft/release-flow.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **ethomson**

**Comment by juliakm** [comment]
I apologize for the delay in responding. Closing because the article has since been rewritten.
