### ISSUE TITLE
Question on porting changes to two branches

### ISSUE THREAD

**Issue by dmossakowski** [MicrosoftDocs/devops-resource-center#38]
Hello, this article seemed like exactly the place that I needed to answer my question on how to port some changes across multiple branches that require a pull request but in the end it actually didn't so here goes.

_"if we need to hotfix a change in the middle of a deployment, we may need to hotfix two different releases: the sprint 129 release and the sprint 130 release. In these cases, **we'll port the hotfix** to both release branches and deploy both release branches. "_ 

In the above statement, what does it means for you to 'port' the changes? Do you cherry pick the same pull request onto two different branches to create two pull requests? For later merges don't the different commit id cause issues?

What about a flow such as this:
- with develop, release/1 and release/2 branches in play 
- with a hotfix needed for release/1 create branch hotfix/bigBadBug from release/1
- do a pull request of hotfix/bigBadBug to release/1 using normal merge type (not squash, not no-ff) but do not delete the branch in the pull request
- do another pull request of the hotfix into release/2 again using normal merge
- do a third pull request of the hotfix into develop branch

Would this work? That should preserve the commit ids across the different branches also. Or is the commit id not really important and it's ok to let git figure out textually whether something is differnt?

One worry with cherrypicking individual pull requests is the situation where you reverse the order. If you cherry pick a later commit and then cherry pick an earlier one, the destination branch does not know the history and might not do what you expect. Or will it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1235ec4-e7e9-b0c2-8f1f-ee9682175a05
* Version Independent ID: a473750a-fbb6-4eed-e0e6-34e8a5009507
* Content: [Release Flow - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow)
* Content Source: [docs/devops-at-microsoft/release-flow.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/devops-at-microsoft/release-flow.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **ethomson**

**Comment by juliakm** [comment]
Closing because this section is no longer in the article.
