### ISSUE TITLE
Rename (Visual Studio) Team Services to Azure DevOps

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/devops-resource-center#4]
I think this page needs to be updated since Team Services (and Visual Studio Team Services) is renamed to Azure DevOps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8667d8-b308-04de-59c6-e437bb4f025d
* Version Independent ID: d65ee06a-98d1-6d7c-a396-9947437d6617
* Content: [Learn Git with Team Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/learn-git-with-team-services)
* Content Source: [docs/git/learn-git-with-team-services.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/git/learn-git-with-team-services.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **routlaw**

**Comment by larryclaman** [comment]
Agreed.  This article is in dire need of a refresh.
