### ISSUE TITLE
Performance of TFS to GIT repository

### ISSUE THREAD

**Issue by vishalgoyal16444** [MicrosoftDocs/devops-resource-center#43]
The process of doing TFS to GIT migration takes very long. We wanted to know what all factors impact the migration and what can be done to speed it up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44afc4fe-66c8-a745-0037-00748a80beb7
* Version Independent ID: 0ea09401-6a08-d745-ff50-7a7b74c41f32
* Content: [Migrate from TFVC to Git - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/migrate-from-tfvc-to-git)
* Content Source: [docs/git/migrate-from-tfvc-to-git.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/git/migrate-from-tfvc-to-git.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **routlaw**

**Comment by pabrams** [comment]
exclude history?

**Comment by juliakm** [comment]
The article is no longer active.
