### ISSUE TITLE
How to for practices in ADO Pipelines

### ISSUE THREAD

**Issue by zesameri** [MicrosoftDocs/devops-resource-center#45]
These practices are great, would love it if it had a how to in ADO pipelines for each of the practices

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71ab8e86-92f0-0e26-b067-5e4ad3362f01
* Version Independent ID: 8f4749ba-b9e5-7d3b-1c5f-4ff666f940a9
* Content: [Safe deployment practices - Azure DevOps](https://docs.microsoft.com/en-us/devops/operate/safe-deployment-practices)
* Content Source: [docs/operate/safe-deployment-practices.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/operate/safe-deployment-practices.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks for the feedback! You can find out more about Azure DevOps security [here](https://learn.microsoft.com/azure/devops/organizations/security/quick-reference-index-security?view=azure-devops), [here](https://learn.microsoft.com/azure/devops/organizations/security/data-protection?view=azure-devops), and [here](https://learn.microsoft.com/azure/security/).
