### ISSUE TITLE
Content was deleted without a redirection

### ISSUE THREAD

**Issue by Youssef1313** [MicrosoftDocs/devops-resource-center#47]
This page was deleted without adding a proper redirection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36dc0671-e3f2-bfc4-7a81-e4e4a7bc4b46
* Version Independent ID: 71ff1404-5a2f-acf3-bdbf-d58adf281cca
* Content: [What is Infrastructure as Code? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/what-is-infrastructure-as-code)
* Content Source: [https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/what-is-infrastructure-as-code.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/what-is-infrastructure-as-code.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Looks like this has since been fixed.
