### ISSUE TITLE
Missing reference to Pulumi

### ISSUE THREAD

**Issue by PabloStraub** [MicrosoftDocs/devops-resource-center#49]
[Enter feedback here]
I was missing a reference to Pulumi at the end. It may even have a link to [Introduction to Infrastructure as Code on Azure using Python with Pulumi](https://devblogs.microsoft.com/devops/infrastructure-as-code-azure-python-wpulumi/).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7183055-0911-8a05-2ab4-f5721085f1a2
* Version Independent ID: d386fb3e-3009-30f1-6512-b5585d149cf4
* Content: [What is Infrastructure as Code? - Azure DevOps](https://docs.microsoft.com/en-us/devops/deliver/what-is-infrastructure-as-code?WT.mc_id=devops-9664-debryen)
* Content Source: [docs/deliver/what-is-infrastructure-as-code.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/deliver/what-is-infrastructure-as-code.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks, looks like that reference has since been added.
