### ISSUE TITLE
Definition of Technical Debt seems incorrect

### ISSUE THREAD

**Issue by pabrams** [MicrosoftDocs/devops-resource-center#51]
Your [definition for technical debt](https://docs.microsoft.com/en-us/devops/plan/what-is-agile-development#minimize-technical-debt) seems incorrect, to me.  Technical debt is not bugs and issues; it's poorly written code (which may be occasionally captured as an issue or bug, but not normally).  Ref: [Wikipedia](https://en.wikipedia.org/wiki/Technical_debt); [MartinFowler.com](https://martinfowler.com/bliki/TechnicalDebt.html); [BMC.com](https://www.bmc.com/blogs/technical-debt-explained-the-complete-guide-to-understanding-and-dealing-with-technical-debt/); [Atlassian.com](https://www.atlassian.com/agile/software-development/technical-debt); [productplan.com](https://www.productplan.com/glossary/technical-debt/)
More pertinently: https://www.scrum.org/forum/scrum-forum/31413/are-defects-technical-debt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9885023d-5dcd-6038-3179-9e9bd40545a0
* Version Independent ID: 91817124-e6ec-e1f1-c892-8f3d27f1fff4
* Content: [What is Agile Development? - Azure DevOps](https://docs.microsoft.com/en-us/devops/plan/what-is-agile-development#minimize-technical-debt)
* Content Source: [docs/plan/what-is-agile-development.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/plan/what-is-agile-development.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by WilliamAntonRohm** [comment]
#assign JKirsch1

**Comment by JKirsch1** [comment]
PR 56, [1967065 | Refresh DevOps resource center content | 2](https://github.com/MicrosoftDocs/devops-learn-pr/pull/56) updates the definition of technical debt in [What is Agile Development?](https://docs.microsoft.com/en-us/devops/plan/what-is-agile-development).
