### ISSUE TITLE
Spelling mistake in last paragraph

### ISSUE THREAD

**Issue by keithjohnmarshall13** [MicrosoftDocs/devops-resource-center#52]
Hi,

great overview, just to be very picky, there is a spelling mistake in the link in the last paragraph. 

"safe deployment pratices" rather than "safe deployment practices"
have a great day!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cf98c4b-9185-00d5-a980-e2adb3e291fd
* Version Independent ID: f6005931-c9b5-48d9-e6c3-f835bb9b01b1
* Content: [What is DevOps? - Azure DevOps](https://docs.microsoft.com/en-us/devops/what-is-devops)
* Content Source: [docs/what-is-devops.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/what-is-devops.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thanks for the feedback! I fixed the typo.
