### ISSUE TITLE
Inconsistent terms in the "Test Taxonomy" section

### ISSUE THREAD

**Issue by crhaglun** [MicrosoftDocs/devops-resource-center#58]
The section "Test Taxonomy" defines L0, L1, L2 and L3 but the final paragraph mentions **L4** as well;

> While the expectation may be that developers always run through L2 before committing, a PR may automatically fail if the L3 test run fails, and the deployment may be blocked if **L4** tests fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dfaa99b-6a0f-1fdd-4d53-bca173b63a9b
* Version Independent ID: d376563c-e46e-91df-576e-ee68a299614e
* Content: [Shift left to make testing fast and reliable - Azure DevOps](https://docs.microsoft.com/en-us/devops/develop/shift-left-make-testing-fast-reliable)
* Content Source: [docs/develop/shift-left-make-testing-fast-reliable.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/develop/shift-left-make-testing-fast-reliable.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Looks like this has been updated.
