### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by n82williams** [MicrosoftDocs/devops-resource-center#59]
practices that consistenty succeed.

Spelling error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1935e29d-37e1-e9ab-f77e-c8f6b3fd7155
* Version Independent ID: 23ff74e9-58ef-17ba-04b0-fe22f0f1e07c
* Content: [Plan your migration to Git - Azure DevOps](https://docs.microsoft.com/en-us/devops/develop/git/centralized-to-git)
* Content Source: [docs/develop/git/centralized-to-git.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/develop/git/centralized-to-git.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thank you! Fixed in main, will be published soon.
