### ISSUE TITLE
Further questions about your testing and CI process

### ISSUE THREAD

**Issue by rkieslinger** [MicrosoftDocs/devops-resource-center#62]
Thank you so much for sharing these insights! As I read through your article, some further questions came to my mind which I would like to ask you:

- Are developers in the described team run tests locally and/or are they running CI builds on topic-/feature-branches **before** opening a PR?
- Are you using incremental builds to achieve these speedy builds?
- How are you handling unit tests which require a sql server? Do you reset the database after every test?

Thank you so much in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dfaa99b-6a0f-1fdd-4d53-bca173b63a9b
* Version Independent ID: d376563c-e46e-91df-576e-ee68a299614e
* Content: [Shift left to make testing fast and reliable - Azure DevOps](https://docs.microsoft.com/en-us/devops/develop/shift-left-make-testing-fast-reliable)
* Content Source: [docs/develop/shift-left-make-testing-fast-reliable.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/develop/shift-left-make-testing-fast-reliable.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks, I'll add this to our feature request list. In the meantime, you may find this [recent blog post helpful](https://www.microsoft.com/insidetrack/blog/streamlining-engineering-at-microsoft-with-azure-devops/).
