### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by wovas** [MicrosoftDocs/devops-resource-center#63]
_They are learning to scale Agile principles with **our** without popular frameworks such as SAFe, LeSS, or Nexus._

should be
_They are learning to scale Agile principles with **or** without popular frameworks such as SAFe, LeSS, or Nexus._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44cba28c-9a39-dc23-a759-759713bb95dc
* Version Independent ID: 0c7e5dc2-0023-de97-aee9-43ddd95c33ba
* Content: [Scaling Agile to large teams - Azure DevOps](https://docs.microsoft.com/en-us/devops/plan/scaling-agile)
* Content Source: [docs/plan/scaling-agile.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/plan/scaling-agile.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks, looks like this has since been fixed.
