### ISSUE TITLE
Page should be updated to match the latest Scrum Guide

### ISSUE THREAD

**Issue by rhundhausen** [MicrosoftDocs/devops-resource-center#65]
Friends,

I'd love to see this page (and a few related pages) updated to reflect the latest Scrum Guide (Nov 2020) - https://scrumguides.org.
In addition, I'd love to see my Microsoft Press book referenced on these pages because I dive deep into all these related subjects:
https://www.microsoftpressstore.com/store/professional-scrum-development-with-azure-devops-9780136789239.

Thanks for listening to my feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd3e1175-0a29-6ffe-cda9-63f419faf371
* Version Independent ID: 54ff8cb0-4c46-a34b-969d-710f3404bd8c
* Content: [What is Scrum? - Azure DevOps](https://docs.microsoft.com/en-us/devops/plan/what-is-scrum)
* Content Source: [docs/plan/what-is-scrum.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/plan/what-is-scrum.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks, I believe this has since been updated.

**Comment by rhundhausen** [comment]
Did you consider listing my book? It's an exact match for that page.
