### ISSUE TITLE
Links to Import from TFVC tool are broken

### ISSUE THREAD

**Issue by jaspecla** [MicrosoftDocs/devops-resource-center#66]
All links to the TFVC to Git tool in Azure DevOps are 404 on this page.  The links read "https://docs.microsoft.com/en-us/azure/devops/git/import-from-tfvc" which is 404, but I believe they should read "https://docs.microsoft.com/en-us/azure/devops/repos/git/import-from-tfvc"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88ee395-2aad-fd11-a95d-dd83b2ec35e6
* Version Independent ID: 05f543c1-b8e6-5bc4-9743-c0204268fecd
* Content: [Migrate from TFVC to Git - Azure DevOps](https://docs.microsoft.com/en-us/devops/develop/git/migrate-from-tfvc-to-git)
* Content Source: [docs/develop/git/migrate-from-tfvc-to-git.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/develop/git/migrate-from-tfvc-to-git.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks, looks like this has since been fixed.
