### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by RobinDijkstra** [MicrosoftDocs/devops-resource-center#67]
The link in "Check in to TFVC and perform the migration" is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88ee395-2aad-fd11-a95d-dd83b2ec35e6
* Version Independent ID: 05f543c1-b8e6-5bc4-9743-c0204268fecd
* Content: [Migrate from TFVC to Git - Azure DevOps](https://docs.microsoft.com/en-us/devops/develop/git/migrate-from-tfvc-to-git)
* Content Source: [docs/develop/git/migrate-from-tfvc-to-git.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/develop/git/migrate-from-tfvc-to-git.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Looks like that link is no longer on the page.
