### ISSUE TITLE
'branch policies' link is returning 404 error

### ISSUE THREAD

**Issue by miwaniza** [MicrosoftDocs/devops-resource-center#68]
In the [Branch policies](https://docs.microsoft.com/en-us/devops/develop/git/what-is-git#branch-policies) section the link is returning 404 error: [Branch policies](https://docs.microsoft.com/en-us/azure/devops/git/branch-policies)

Probably, it should be updated with the new one: [About branches and branch policies](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies-overview?view=azure-devops).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae1ac1da-741f-b359-c0c3-6d153d29a0f2
* Version Independent ID: 2115b917-1f35-b045-439c-059c5a1a35c1
* Content: [What is Git? - Azure DevOps](https://docs.microsoft.com/en-us/devops/develop/git/what-is-git#feedback)
* Content Source: [docs/develop/git/what-is-git.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/develop/git/what-is-git.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
This link has since been updated.
