### ISSUE TITLE
Git LFS doesn't stand for "Large File Support" but "Large File Storage"

### ISSUE THREAD

**Issue by mkennten** [MicrosoftDocs/devops-resource-center#70]
Git LFS doesn't stand for "Large File Support" but "Git Large File Storage", see https://git-lfs.github.com/.

Used in:
These assets should use the Git LFS (Large File Support) extension, which the import tool does not configure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88ee395-2aad-fd11-a95d-dd83b2ec35e6
* Version Independent ID: 05f543c1-b8e6-5bc4-9743-c0204268fecd
* Content: [Migrate from TFVC to Git - Azure DevOps](https://docs.microsoft.com/en-us/devops/develop/git/migrate-from-tfvc-to-git)
* Content Source: [docs/develop/git/migrate-from-tfvc-to-git.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/develop/git/migrate-from-tfvc-to-git.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks! An update will go out shortly.
