### ISSUE TITLE
Wording issue

### ISSUE THREAD

**Issue by lorrinferdinand** [MicrosoftDocs/devops-resource-center#71]
Note that highlighted  "our" should be "or"

![image](https://user-images.githubusercontent.com/15255737/156925269-689eadb8-bff6-4b59-a68a-a3a7b513dc8e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44cba28c-9a39-dc23-a759-759713bb95dc
* Version Independent ID: 0c7e5dc2-0023-de97-aee9-43ddd95c33ba
* Content: [Scaling Agile to large teams - Azure DevOps](https://docs.microsoft.com/en-us/devops/plan/scaling-agile)
* Content Source: [docs/plan/scaling-agile.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/plan/scaling-agile.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thank you for the feedback, @lorrinferdinand ! FYI, you're welcome to make changes to the document yourself--just click the edit button on the upper-right corner of the page to begin the process.

**Comment by juliakm** [comment]
This has since been fixed.
