### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by sabuncumurat** [MicrosoftDocs/devops-resource-center#73]
In section titled 'Understand branch history', the command:

`git merge cool-feature master`

needs to be:

`git merge cool-new-feature master`

Not the end of the world, I know. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6c7f339-1705-5225-b913-b3009a429084
* Version Independent ID: a33e94de-6b69-2f20-2bcc-333739e75049
* Content: [Understand Git history - Azure DevOps](https://docs.microsoft.com/en-us/devops/develop/git/understand-git-history)
* Content Source: [docs/develop/git/understand-git-history.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/develop/git/understand-git-history.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks! We've fixed this.
