### ISSUE TITLE
Dead link for "Secure your code's dependencies"

### ISSUE THREAD

**Issue by klecouvey** [MicrosoftDocs/devops-resource-center#74]
In section [Secure your code with GitHub](https://docs.microsoft.com/en-us/devops/devsecops/enable-devsecops-azure-github#secure-your-code-with-github), the link [Secure your code's dependencies](https://help.github.com/github/managing-security-vulnerabilities/managing-vulnerabilities-in-your-projects-dependencies) is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a1d4f15-b16d-0b23-d1d2-9dda21c12107
* Version Independent ID: 2a1d4f15-b16d-0b23-d1d2-9dda21c12107
* Content: [Enable DevSecOps with Azure and GitHub - Azure DevOps](https://docs.microsoft.com/en-us/devops/devsecops/enable-devsecops-azure-github)
* Content Source: [docs/devsecops/enable-devsecops-azure-github.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/devsecops/enable-devsecops-azure-github.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by whihathac** [comment]
Should point to - https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql

**Comment by juliakm** [comment]
Looks like this has been fixed.
