### ISSUE TITLE
Why Bicep is not included in this document as an IaC option ?

### ISSUE THREAD

**Issue by mrunalbrahmbhatt** [MicrosoftDocs/devops-resource-center#75]
Hi Team,

I'm preparing RFT for the customer, I'm a Microsoft employee and would like to know why **Bicep** is not included in this document as an IaC option?

Thanks,
Mrunal
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7183055-0911-8a05-2ab4-f5721085f1a2
* Version Independent ID: d386fb3e-3009-30f1-6512-b5585d149cf4
* Content: [What is Infrastructure as Code? - Azure DevOps](https://docs.microsoft.com/en-us/devops/deliver/what-is-infrastructure-as-code)
* Content Source: [docs/deliver/what-is-infrastructure-as-code.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/deliver/what-is-infrastructure-as-code.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Sorry for the late response. I'm updating the article to include Bicep.

**Comment by mrunalbrahmbhatt** [comment]
Thanks Julia.
