### ISSUE TITLE
Typo fix

### ISSUE THREAD

**Issue by douglasgaigher** [MicrosoftDocs/devops-resource-center#76]
There is a typo at the third paraph:

_**Deveopers**_ work with Git through commands issued while working in a local repo on the computer. Even when sharing code or getting updates from the team, it's done from commands that update the local repo. This local-focused design is what makes Git a distributed version control system. Every repo is self-contained, and the owner of the repo is responsible for keeping it up to date with the changes from others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d06367e1-3d5b-70fc-5b21-ff9209b711e3
* Version Independent ID: 21d2ef7f-54f4-7f1e-3fd4-1965ac1f4609
* Content: [Set up a repository - Azure DevOps](https://docs.microsoft.com/en-us/devops/develop/git/set-up-a-git-repository)
* Content Source: [docs/develop/git/set-up-a-git-repository.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/develop/git/set-up-a-git-repository.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Closing as this is resolved.
