### ISSUE TITLE
Should we also mention Split.IO?

### ISSUE THREAD

**Issue by DaveBurnisonMS** [MicrosoftDocs/devops-resource-center#78]
This page mentions Launch Darkly by name. Should we also reference Split.IO? See
- https://www.split.io/blog/split-azure-devops-integration
- https://marketplace.visualstudio.com/items?itemName=SplitSoftware.split-for-azuredevops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a814db-9723-9c69-3165-ca67c17915d3
* Version Independent ID: 9827407f-bb04-0a27-4332-c4d34915256d
* Content: [Progressive experimentation with feature flags - Azure DevOps](https://docs.microsoft.com/en-us/devops/operate/progressive-experimentation-feature-flags)
* Content Source: [docs/operate/progressive-experimentation-feature-flags.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/operate/progressive-experimentation-feature-flags.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks! This is an older issue but I wanted to let you know that a mention of Split will get added this week.
