### ISSUE TITLE
Need to cross reference Bicep

### ISSUE THREAD

**Issue by robm82** [MicrosoftDocs/devops-resource-center#79]
This page appears to need a reference to Bicep for the IaC model for Azure. Great that you link to resources like Terraform and Ansible, but it might be beneficial to promote Bicep :).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7183055-0911-8a05-2ab4-f5721085f1a2
* Version Independent ID: d386fb3e-3009-30f1-6512-b5585d149cf4
* Content: [What is Infrastructure as Code? - Azure DevOps](https://docs.microsoft.com/en-us/devops/deliver/what-is-infrastructure-as-code)
* Content Source: [docs/deliver/what-is-infrastructure-as-code.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/deliver/what-is-infrastructure-as-code.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks, we will add a Bicep mention this week.
