### ISSUE TITLE
Adding link to Scrum Guide to What is Scrum? page

### ISSUE THREAD

**Issue by ravivajaria** [MicrosoftDocs/devops-resource-center#80]
I think providing link to the Scrum Guide - the official Scrum Body of Knowledge - would add value an valuable to the readers. I think best place would be to add a line in first paragraph as below. 

Scrum Framework is defined in [The Scrum Guide (TM)](https://scrumguides.org/) and written by Ken Schwaber and Jeff Sutherland, co-creators of Scrum.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd3e1175-0a29-6ffe-cda9-63f419faf371
* Version Independent ID: 54ff8cb0-4c46-a34b-969d-710f3404bd8c
* Content: [What is Scrum? - Azure DevOps](https://docs.microsoft.com/en-us/devops/plan/what-is-scrum)
* Content Source: [docs/plan/what-is-scrum.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/plan/what-is-scrum.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks for the feedback. We've received this feedback before as well and will check with the team on adding the link.
