### ISSUE TITLE
Expired certificate on DevOps Self-Assessment link

### ISSUE THREAD

**Issue by v-thepet** [MicrosoftDocs/devops-resource-center#81]
The link to DevOps Self-Assessment: https://devopsassessment.net/ is throwing a privacy/security error and says the certificate expired 70 days ago. Please renew the certificate ASAP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 885f49c6-ea72-8b23-f2c5-c99518456e3e
* Version Independent ID: faa80f9b-6dc8-bbd0-1b60-69c2d0d6311c
* Content: [DevOps Resource Center - Azure DevOps](https://docs.microsoft.com/en-us/devops/)
* Content Source: [docs/index.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/index.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Looks like this is now resolved.
