### ISSUE TITLE
already is spelled wrong -> alredy 

### ISSUE THREAD

**Issue by ethos-tim** [MicrosoftDocs/devops-resource-center#83]
already is spelled wrong -> alredy 

Kanban helps teams focus on maintaining an agreed-upon level of quality. This measure must be met before a team can claim a piece of work is done. To support this model, stakeholders do not push work upon teams that are alredy working at capacity. Instead, they add requests to a backlog that the team "pulls" into their workflow as capacity becomes available.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0dd2a5a-22fe-cb58-9dd9-f6723fad6881
* Version Independent ID: ae1f39fe-d451-bc15-fa95-d4744909035f
* Content: [What is Kanban? - Azure DevOps](https://docs.microsoft.com/en-us/devops/plan/what-is-kanban)
* Content Source: [docs/plan/what-is-kanban.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/plan/what-is-kanban.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Looks like it's already been fixed, thanks!
