### ISSUE TITLE
github actions link is broken in page

### ISSUE THREAD

**Issue by sergiosolorzano** [MicrosoftDocs/devops-resource-center#84]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65da4c36-9580-2f30-758f-258f636abecc
* Version Independent ID: 6238066e-aa04-879f-1d9c-7fc3f1295fae
* Content: [What is continuous delivery? - Azure DevOps](https://docs.microsoft.com/en-us/devops/deliver/what-is-continuous-delivery)
* Content Source: [docs/deliver/what-is-continuous-delivery.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/deliver/what-is-continuous-delivery.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Looks like the link works now.
