### ISSUE TITLE
Typo in "Eliminate downtime through versioned service updates"

### ISSUE THREAD

**Issue by sergey-akhalkov** [MicrosoftDocs/devops-resource-center#85]
Actual: B**u** using versioned updates
Expected: B**y** using versioned updates

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72a3f80d-687c-b000-bfa9-bfd9c6d7d107
* Version Independent ID: 2842a12d-9e2c-a947-0acf-52d5faa9a1d1
* Content: [Eliminate downtime through versioned service updates - Azure DevOps](https://learn.microsoft.com/en-us/devops/operate/achieving-no-downtime-versioned-service-updates?source=docs#feedback)
* Content Source: [docs/operate/achieving-no-downtime-versioned-service-updates.md](https://github.com/MicrosoftDocs/devops-resource-center-pr/blob/live/docs/operate/achieving-no-downtime-versioned-service-updates.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks! An update will roll out this week.
