### ISSUE TITLE
Statement needs correction

### ISSUE THREAD

**Issue by davins-msft** [MicrosoftDocs/devops-resource-center#86]
The following statement needs correction:
 "DevOps lets formerly siloed roles like development, IT operations, quality engineering, and security coordinate and collaborate."

It seems that a word "to" is missing in the statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0cf98c4b-9185-00d5-a980-e2adb3e291fd
* Version Independent ID: f6005931-c9b5-48d9-e6c3-f835bb9b01b1
* Content: [What is DevOps? - Azure DevOps](https://learn.microsoft.com/en-us/devops/what-is-devops)
* Content Source: [docs/what-is-devops.md](https://github.com/MicrosoftDocs/devops-resource-center-pr/blob/live/docs/what-is-devops.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks, this has since been updated.
