### ISSUE TITLE
No mention of Azure Bicep

### ISSUE THREAD

**Issue by DanGEvans** [MicrosoftDocs/devops-resource-center#89]
You mention third parties at the bottom of the page and mention ARM template deployments but not used the opportunity to advise  about Microsoft's own IaC, Bicep.   I think it is sensible to point readers to Microsoft's own IaC language, rather than jump straight to third party suggestions as further adoption of Bicep will lead to more development, more community and more help pages.   Ideally linking to the [What is Bicep?](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview?tabs=bicep) learning page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7183055-0911-8a05-2ab4-f5721085f1a2
* Version Independent ID: d386fb3e-3009-30f1-6512-b5585d149cf4
* Content: [What is infrastructure as code (IaC)? - Azure DevOps](https://learn.microsoft.com/en-us/devops/deliver/what-is-infrastructure-as-code?source=docs#feedback)
* Content Source: [docs/deliver/what-is-infrastructure-as-code.md](https://github.com/MicrosoftDocs/devops-resource-center-pr/blob/live/docs/deliver/what-is-infrastructure-as-code.md)
* Service: **azure-devops**
* Sub-service: **devops-resource-center**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks, we'll add a Bicep reference this week.
