### ISSUE TITLE
How can you build and run unit tests so fast

### ISSUE THREAD

**Issue by rkieslinger** [MicrosoftDocs/devops-resource-center#90]
How is it possible for you to build almost 3k projects (C# and slow C++ projects) and run 60k unit tests in 30 minutes?

Do you use incremental builds or how do you do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dfaa99b-6a0f-1fdd-4d53-bca173b63a9b
* Version Independent ID: d376563c-e46e-91df-576e-ee68a299614e
* Content: [Shift testing left with unit tests - Azure DevOps](https://learn.microsoft.com/en-us/devops/develop/shift-left-make-testing-fast-reliable)
* Content Source: [docs/develop/shift-left-make-testing-fast-reliable.md](https://github.com/MicrosoftDocs/devops-resource-center-pr/blob/live/docs/develop/shift-left-make-testing-fast-reliable.md)
* Service: **azure-devops**
* Sub-service: **devops-resource-center**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by StingyJack** [comment]
Granted that I've never had anywhere near that amount of tests, depending on the size of the projects that may be doable...
- 3K projects in 30 minutes ~= 100 projects per minute. A few years ago I had a 250 project solution of both large and small projects, some UI, some Web, some WinSvc, etc... that VS 2015 could build in ~2 minutes on an HP laptop with 16GB ram and 4 dual core CPU's.   
- 60K unit tests in 30 minutes = 2K tests per minute = ~33 tests per second.  Tiny tests only take a few MS to run. 

I remember reading a few years ago that they do use incremental builds and several other tricks.  

It probably helps to be the author of both the build and the testing tools, and priority access to those teams

**Comment by juliakm** [comment]
Closing because I haven't been able to track down the exact source. It looks like [ML Ops Foundations](https://microsoft.github.io/azureml-ops-accelerator/1-MLOpsFoundation/) uses the same number and you may find that content helpful.
