### ISSUE TITLE
Everything under the DevOps Resource Center should be moved out from under the Azure DevOps product documentation

### ISSUE THREAD

**Issue by timothymeyers** [MicrosoftDocs/devops-resource-center#91]
This section of our Docs is just DevOps Hub that covers information for a variety of products, including -- and leading with -- GitHub, AZD, VSC. Azure DevOps is just one of those products.

Azure DevOps is a confusingly named product, and having all of this more general information aligned to the Azure DevOps product documentation exacerbates the issue.

In truth, it appears that /devops is not even contained within the /azure/devops subsites of our documentation. So, I'm not sure why this page says Azure DevOps in the title or has the Azure DevOps branding.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 885f49c6-ea72-8b23-f2c5-c99518456e3e
* Version Independent ID: faa80f9b-6dc8-bbd0-1b60-69c2d0d6311c
* Content: [DevOps resource center - Azure DevOps](https://learn.microsoft.com/en-us/devops/)
* Content Source: [docs/index.md](https://github.com/MicrosoftDocs/devops-resource-center-pr/blob/live/docs/index.md)
* Service: **azure-devops**
* Sub-service: **devops-resource-center**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks, we've moved a lot of the content out based on this suggestion.
