### ISSUE TITLE
We should add a section on Microsoft's internal use of GitHub Copilot on this page

### ISSUE THREAD

**Issue by DaveBurnisonMS** [MicrosoftDocs/devops-resource-center#93]
We should add a section on Microsoft's internal use of GitHub Copilot on this page. We need to highlight to the world that Microsoft is now internally using Copilot. Sellers often share the DevOps Resource Center with customers so this would be a great avenue to share how Microsoft engineers are seeing productivity gains from using Copilot. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9e67f55-3915-bc7e-5d78-e7f0ee72a6f1
* Version Independent ID: 0280a766-ed9d-c9fe-9f86-d81f4eec26fe
* Content: [How Microsoft develops with DevOps - Azure DevOps](https://learn.microsoft.com/en-us/devops/develop/how-microsoft-develops-devops)
* Content Source: [docs/develop/how-microsoft-develops-devops.md](https://github.com/MicrosoftDocs/devops-resource-center-pr/blob/live/docs/develop/how-microsoft-develops-devops.md)
* Service: **azure-devops**
* Sub-service: **devops-resource-center**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks @DaveBurnisonMS! Sorry for the delay in responding. Adding Copilot makes a lot of sense. We're adding this to our backlog. Can you send any resources you happen to have on MSFT's internal use of Copilot to me?
