### ISSUE TITLE
Can this expand on the testing methods, schedules, and gating activities?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/devops-resource-center#94]
A few orgs I have worked at/with tend to follow a similar approach to this, but struggle with testing activities. Can some more detail be added to give customers a more solid idea about one of the ways it can be done?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9e67f55-3915-bc7e-5d78-e7f0ee72a6f1
* Version Independent ID: 0280a766-ed9d-c9fe-9f86-d81f4eec26fe
* Content: [How Microsoft develops with DevOps - Azure DevOps](https://learn.microsoft.com/en-us/devops/develop/how-microsoft-develops-devops)
* Content Source: [docs/develop/how-microsoft-develops-devops.md](https://github.com/MicrosoftDocs/devops-resource-center-pr/blob/live/docs/develop/how-microsoft-develops-devops.md)
* Service: **azure-devops**
* Sub-service: **devops-resource-center**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks @StingyJack. Adding your feedback to our backlog. This article could definitely use more details on testing.
