### ISSUE TITLE
No mention of Bicep

### ISSUE THREAD

**Issue by alindgren** [MicrosoftDocs/devops-resource-center#96]
Just a suggestion, but it seems like a mention of Bicep would be good in the last section.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7183055-0911-8a05-2ab4-f5721085f1a2
* Version Independent ID: d386fb3e-3009-30f1-6512-b5585d149cf4
* Content: [What is infrastructure as code (IaC)? - Azure DevOps](https://learn.microsoft.com/en-us/devops/deliver/what-is-infrastructure-as-code)
* Content Source: [docs/deliver/what-is-infrastructure-as-code.md](https://github.com/MicrosoftDocs/devops-resource-center-pr/blob/live/docs/deliver/what-is-infrastructure-as-code.md)
* Service: **azure-devops**
* Sub-service: **devops-resource-center**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks, we'll add a Bicep reference this week.
