### ISSUE TITLE
git-tfs ??

### ISSUE THREAD

**Issue by GregBartlett** [MicrosoftDocs/devops-resource-center#97]
I'm seeing more and more that TFVC is going the way of the dodo, but you all are referencing the git-tfs tool, and whomever is maintaining it isn't supporting it anymore.

"This project is no more actively maintained because we are no more users of TFS. Thus being very useful, git-tfs is not exempt of not supported use cases. If you encounter something missing or a problem, please contribute, we will be pleased to help you."

I guess my feedback is, if you want people to move, it would be helpful to have the appropriate, supported, tools needed to do the same.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e88ee395-2aad-fd11-a95d-dd83b2ec35e6
* Version Independent ID: 05f543c1-b8e6-5bc4-9743-c0204268fecd
* Content: [Migrate from TFVC to Git - Azure DevOps](https://learn.microsoft.com/en-us/devops/develop/git/migrate-from-tfvc-to-git)
* Content Source: [docs/develop/git/migrate-from-tfvc-to-git.md](https://github.com/MicrosoftDocs/devops-resource-center-pr/blob/live/docs/develop/git/migrate-from-tfvc-to-git.md)
* Service: **azure-devops**
* Sub-service: **devops-resource-center**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks for the feedback. We'll bring it to the product team.
